version: '3.1'
services:
  db_py:
    container_name: pg_container_py
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
      POSTGRES_DB: db
    ports:
      - "5435:5432"
    volumes:
      - ./data-py:/var/lib/postgresql/data