version: '3'

services:
  web:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db_py
  db_py:
    image: postgres
    container_name: pg_container_py
    environment:
      POSTGRES_DB: 
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
    volumes:
      - ./data-py:/var/lib/postgresql/data

volumes:
  db_data: